### ISSUE TITLE
Blank page if saved with no teams

### ISSUE THREAD

**Issue by jacksmirk** [yuya-oc/electron-mattermost#11]
First time I open the application it shows a form to add teams. I mistakedly clicked on save without adding any teams and it went blank. I have closed the application and opened it several times and it shows a blank page every time.

**Comment by smackjack3** [comment]
I think you need to go back to Settings from the electron-mattermost menu option and then enter a team.

**Comment by yuya-oc** [comment]
Thanks, @smackjack3.

On Windows, please press Alt key to show menu bar.

**Comment by jacksmirk** [comment]
Thanks a lot, that solved it but it would be better to add validation so it doesn't let you save unless you add at least a team.
