### ISSUE TITLE
Horizontal Scrollbar

### ISSUE THREAD

**Issue by stefuNz** [yuya-oc/electron-mattermost#16]
Currently using Mattermost 1.3, it is showing a horizontal scrollbar on the bottom which is unnecessary.
Tested with Windows and Mac OS X

**Comment by yuya-oc** [comment]
I can't see horizontal scrollbar. Sorry, I can't prepare Mattermost 1.3 soon now.
Would you check following points?

* Is the problem reproduced on Chrome?
* Please try "Clear Cache and Reload" (`Shift+Ctrl+R` or `Shift+Command+R`)

**Comment by stefuNz** [comment]
reproduced in chrome and still existing after clear cache and reload

**Comment by yuya-oc** [comment]
Then, I think it's the issue of Mattermost (or Chrome).

**Comment by it33** [comment]
Yes, sorry, Mattermost server issue that should be fixed in Mattermost v1.4

**Comment by yuya-oc** [comment]
Thank you for feedback.
