### ISSUE TITLE
Windows 10 doesn't show setting page.

### ISSUE THREAD

**Issue by Bedotech** [yuya-oc/electron-mattermost#17]
in windows 10 when the program is start doesn't show UI for add and manage teams.
No errors reported in console.

**Comment by yuya-oc** [comment]
My testing environment is also Windows 10. I tried reproducing the problem by reinstalling the app. But I didn't met that.
Would you tell me more detailed info?

* electron-mattermost version.
* Which version is your Windows 10, 32-bit or 64-bit?
* How to reproduce, step-by-step.

**Comment by Bedotech** [comment]
with the new relase it work well! 
Thanks you!
