### ISSUE TITLE
it looks like full node modules are bundled, rather than just the distribution files

### ISSUE THREAD

**Issue by Pomax** [yuya-oc/electron-mattermost#23]
Looking at the 43Mb Windows download, it appears that a full node_modules directory is zipped in, rather than just the files necessary for running the code. This makes the download much, much bigger than it needs to be. Especially if people already have Node installed on their machine, it feels like these dependencies could be left out and downloaded as needed, instead.

![screenshot 117](https://cloud.githubusercontent.com/assets/177243/12566052/83a311a6-c36c-11e5-99d3-2ad5c136983f.png)

**Comment by alerque** [comment]
We should not assume end users will ever have node installed. The main use case I have for this kind of front-end interface is to get non-developers started with a ready-to-use single purpose GUI.

If there are things being bundled that are not used at all, of course it could be trimmed down to just what is required to run, but the bundle should be self contained and ready to roll without further downloading.

**Comment by yuya-oc** [comment]
As @alerque said, the app should work in non-developer's environment. Just download and extract it.

If I could, of course I want to shrink its bundled size. However I'm not good at this topic. Would you tell me whether there is any way?

**Comment by Pomax** [comment]
yeah removing them entirely is probably a bad idea, but most node_modules don't need all the files they come with for the code to work (you don't need the tests and docs and all that if you're using them as actual code dependencies).

I would recommend using something like webpack, which despite having "web" in the name also comes with the ability to bundle "for node", so you can point it at your application code, and it'll generate a full bundle that can as `node app.js` with all the dependencies bundled in and minified.

You basically run webpack and tell it to generate [a library, rather than client bundle], and the result is going to be a *lot* smaller than adding in the node_modules dir.

**Comment by yuya-oc** [comment]
Thanks, I'll check.

**Comment by yuya-oc** [comment]
I tried webpack at 174988a4efae59ab223bf8485bfb329d167e129f.

Most of app's size is occupied by Electron itself. So the size won't be reduced by webpack.
However, the number of files decreases much. This is effective when extracting the archive.

**Comment by Pomax** [comment]
interesting finding, how little of a difference does it make in terms of size?

**Comment by yuya-oc** [comment]
On Windows 64bit:

|version|zip|extracted|files|folders|`resources/app`|
|---|---|---|---|---|---|
|v1.0.3|52.6MB|133MB|3476|270|12.2MB|
|174988a|48.8MB|125MB|105|13|4.06MB|

**Comment by Pomax** [comment]
interesting. Yeah that's not *too* much space saved (although 4mb on 52/48 is still considerable), but that's an amazing reduction in files.

**Comment by yuya-oc** [comment]
v1.0.4 is released. It uses webpack.

**Comment by Pomax** [comment]
you are a hero

**Comment by Pomax** [comment]
btw, perhaps interesting to know, using 7z rather than plain zip for compression gives me a 31MB archive for 1.0.4 (set to best compression, since it's a release pack), rather than 51MB, so that's a drastic savings, too. Might be worth using 7z for future releases.

**Comment by yuya-oc** [comment]
I know 7z can compress better than zip, however, it's not supported by os. So I will use only plain zip. Thanks.
