### ISSUE TITLE
self compiled version doesn´t start (win32/64)

### ISSUE THREAD

**Issue by elpatron68** [yuya-oc/electron-mattermost#24]
Build (under Ubuntu/wine) seems okay:
```
> electron-mattermost@1.0.2 package:windows /home/user/electron-mattermost
> gulp package:windows

[23:01:59] Using gulpfile ~/electron-mattermost/gulpfile.js
[23:01:59] Starting 'sync-meta'...
[23:01:59] Finished 'sync-meta' after 2.94 ms
[23:01:59] Starting 'build:jsx'...
[23:02:00] Finished 'build:jsx' after 1.7 s
[23:02:00] Starting 'build'...
[23:02:00] Finished 'build' after 14 μs
[23:02:00] Starting 'package:windows'...
Packaging app for platform win32 ia32 using electron v0.36.3
Packaging app for platform win32 x64 using electron v0.36.3
[23:02:24] Finished 'package:windows' after 24 s
```

Starting electron-mattermost.exe leads to
`Uncaught exception, Cannot find module yargs`
(see http://imgur.com/IFbIZaw)

**Comment by yuya-oc** [comment]
Could you tell me more info?
* commit id
* node and npm version
* Does `npm start` work?
* Is yargs installed into `node_modules`(src and release) correctly?

Then, I can't test the app for a while. Please wait.

**Comment by elpatron68** [comment]
I tried to build on a console-only VM, so was wasn´t able to start. If that´s likely to be part of the problem, I would try on another machine.

markus@ubuntu:~$ npm -v
2.14.15
markus@ubuntu:~$ node -v
v0.10.41
markus@ubuntu:~/electron-mattermost$ npm ls yargs
electron-mattermost@1.0.2 /home/markus/electron-mattermost
└── yargs@3.32.0  extraneous

commit 1fdc7691d787f7a224fa7f6b1075a35ecace3d27

**Comment by yuya-oc** [comment]
Could you try `npm install` with node 5.x(newer npm) ? Electron v0.36 integrates node 5.1.1, it's used instead of your local node.js.

**Comment by elpatron68** [comment]
I tried my luck with node 5.5.0 and npm 3.3.12 - no luck. I can live with the pre-built release version, so no big problem for me.

**Comment by yuya-oc** [comment]
Just for note:

I tested with cleaned repo.

Env: ubuntu 14.04 64bit, node 5.5.0, npm 3.3.12
-> Windows 10 x64 can start the app.

Besides, I'm using Docker container(debian and wine) for pre-built release version.
