### ISSUE TITLE
Application doesn't show up in the volume mixer in Windows 7

### ISSUE THREAD

**Issue by Jarvil** [yuya-oc/electron-mattermost#29]
Hello,

There seem to be a bug in Electron-mattermost 64bit v1.0.2 it doesn't show up in the Windows volume mixer in Windows 7 at all.

![image](https://cloud.githubusercontent.com/assets/15193418/12776074/aaa4fc7e-ca5b-11e5-829e-a979823d7771.png)

**Comment by alerque** [comment]
In Linux per-app volume controls usually only show up while an app is actually connected to the audio subsystem. Is that not the case on Windows? Are you sure there is nothing there when a sound actually happens?

**Comment by Jarvil** [comment]
Hello,

I think it should show in Windows too since it tries to show it in Windows 10:

https://github.com/yuya-oc/electron-mattermost/issues/28

**Comment by yuya-oc** [comment]
I tried v1.0.3 with Windows 7 32bit. The result is same as #28.

![mixer](https://cloud.githubusercontent.com/assets/1412057/12884816/a92617e4-ce15-11e5-8623-43e6ad9f745d.png)
