### ISSUE TITLE
Desktop notifications not working

### ISSUE THREAD

**Issue by efegurkan** [yuya-oc/electron-mattermost#30]
Hello,

Desktop notifications does not work with a slack account on OS X 10.11.3. I click on enable desktop notifications on slack settings. This alert shows up "huh allowed:false permission_level:undefined".

**Comment by yuya-oc** [comment]
The app is built for **Mattermost**. Could you check again?

**Comment by efegurkan** [comment]
Sure thing,
Works fine with Slack also btw, I will check If I can find a way to make it work without broking it. Maybe this can be used as an open-source slack client also.

Sorry for the noise :smile:

Have a lot of fun.

**Comment by yuya-oc** [comment]
JYFI, the notification might work by removing `src/browser/webview/mattermost.js`. Because it overrides desktop notification in webview.
