### ISSUE TITLE
Notification Settings

### ISSUE THREAD

**Issue by johncooper18** [yuya-oc/electron-mattermost#31]
It would be great to have an option to configure the small red circle icon, that appears in the system tray when someone posts into MatterMost. 
It would be better if it could appear only if someone mentions you. Now it seems to appear every time there is an activity in any of your channels. 
So you would see the channels with unread messages in bold just as now, but the red circle would only appear if someone mentions you.

**Comment by johncooper18** [comment]
Or if there would be two different coloured circles: a green for example for any activity, the red if you are mentioned.

**Comment by yuya-oc** [comment]
On Windows, the red badge appears on the taskbar icon. Is it not enough?

**Comment by johncooper18** [comment]
Hi! It's more than enough - we cannot distinguish between the following cases: 
- "I was mentioned in a channel so it's important to check on mattermost asap", 
- "Something happened in one of my channels, so I will check on it when I have time"

So that's exactly the problem: it seems to appear every time there is an activity in any of your channels. Any activity, any channels. It would be great to have an option to configure this red badge:
A.) Only for mentions.
B.) For all unread messages.

Thank you!

**Comment by yuya-oc** [comment]
How about OS X behavior?

* Mention: numerical badge
* Unread: `●` badge

BTW, the app can't know whether a notification popup is mention. The behavior is changeable in Mattermost(Menu->Account Settings->Notifications).

**Comment by johncooper18** [comment]
Ok could be good. :) If we can see the difference it could be a good solution. Thank you!

**Comment by johncooper18** [comment]
And sry the notification popup works great. Only the small little red badge's working is somehow interesting for us.

**Comment by yuya-oc** [comment]
v1.0.4 is released. It uses numerical badge for mention.

**Comment by johncooper18** [comment]
Works fine, thank you!
