### ISSUE TITLE
Problem building windows binaries

### ISSUE THREAD

**Issue by etcy** [yuya-oc/electron-mattermost#34]
Sorry for sounding noob..
I cannot seem to figure out how to build the binaries for windows. Here is the steps and log I get.
1. clone git, goto dir
2. npm install
3. npm run package:windows

LOG:
```
> electron-mattermost@1.0.5 package:windows /home/user/electron-mattermost
> gulp package:windows

[17:56:50] Using gulpfile ~/electron-mattermost/gulpfile.js
[17:56:50] Starting 'sync-meta'...
[17:56:50] Finished 'sync-meta' after 1.25 ms
[17:56:50] Starting 'webpack:main'...
[17:56:50] Starting 'webpack:browser'...
[17:56:50] Starting 'webpack:webview'...
[17:56:50] Starting 'copy:resources'...
[17:56:50] Starting 'copy:html/css'...
[17:56:50] Starting 'copy:modules'...
[17:56:50] Version: webpack 1.12.13
        Asset     Size  Chunks             Chunk Names
mattermost.js  6.93 kB       0  [emitted]  mattermost
[17:56:51] Finished 'copy:resources' after 1.21 s
[17:56:51] Finished 'webpack:webview' after 1.22 s
[17:56:51] Finished 'copy:html/css' after 1.32 s
[17:56:54] Version: webpack 1.12.13
  Asset    Size  Chunks             Chunk Names
main.js  757 kB       0  [emitted]  main

WARNING in ./src/main.js
Critical dependencies:
117:21-46 the request of a dependency is an expression
 @ ./src/main.js 117:21-46

WARNING in ./src ^\.\/.*$
Module not found: Error: a dependency to an entry point is not allowed
 @ ./src ^\.\/.*$

WARNING in ./src ^\.\/.*$
Module not found: Error: a dependency to an entry point is not allowed
 @ ./src ^\.\/.*$

WARNING in ./src/~/yargs/lib/parser.js
Critical dependencies:
359:21-48 the request of a dependency is an expression
 @ ./src/~/yargs/lib/parser.js 359:21-48

WARNING in ./src/browser/css/jp_fonts.css
Module parse failed: /home/edward/electron-mattermost/src/browser/css/jp_fonts.css Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| @font-face {
|   font-family: sans-serif;
|   src: local('Meiryo UI');
 @ ./src ^\.\/.*$

WARNING in ./src/browser/index.html
Module parse failed: /home/edward/electron-mattermost/src/browser/index.html Line 1: Unexpected token <
You may need an appropriate loader to handle this file type.
| <!DOCTYPE html>
| <html>
| 
 @ ./src ^\.\/.*$

WARNING in ./src/browser/index.jsx
Module parse failed: /home/edward/electron-mattermost/src/browser/index.jsx Line 131: Unexpected token <
You may need an appropriate loader to handle this file type.
|     if (this.props.teams.length > 1) {
|       tabs_row = (
|         <Row>
|           <TabBar id="tabBar" teams={ this.props.teams } unreadCounts={ this.state.unreadCounts } mentionCounts={ this.state.mentionCounts } unreadAtActive={ this.state.unreadAtActive } mentionAtActiveCounts={ this.state.mentionAtActiveCounts }
|             activeKey={ this.state.key } onSelect={ this.handleSelect }></TabBar>
 @ ./src ^\.\/.*$

WARNING in ./src/browser/settings.html
Module parse failed: /home/edward/electron-mattermost/src/browser/settings.html Line 1: Unexpected token <
You may need an appropriate loader to handle this file type.
| <!DOCTYPE html>
| <html>
| 
 @ ./src ^\.\/.*$

WARNING in ./src/browser/settings.jsx
Module parse failed: /home/edward/electron-mattermost/src/browser/settings.jsx Line 65: Unexpected token <
You may need an appropriate loader to handle this file type.
|   render: function() {
|     var teams_row = (
|     <Row>
|       <Col md={ 12 }>
|       <h2>Teams</h2>
 @ ./src ^\.\/.*$

WARNING in ./src/resources/appicon.png
Module parse failed: /home/edward/electron-mattermost/src/resources/appicon.png Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./src ^\.\/.*$

WARNING in ./src/resources/tray.png
Module parse failed: /home/edward/electron-mattermost/src/resources/tray.png Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./src ^\.\/.*$

WARNING in ./src/~/ws/lib/BufferUtil.js
Module not found: Error: Cannot resolve module 'bufferutil' in /home/edward/electron-mattermost/src/node_modules/ws/lib
 @ ./src/~/ws/lib/BufferUtil.js 10:19-40

WARNING in ./src/~/ws/lib/Validation.js
Module not found: Error: Cannot resolve module 'utf-8-validate' in /home/edward/electron-mattermost/src/node_modules/ws/lib
 @ ./src/~/ws/lib/Validation.js 10:19-44

WARNING in ./src/~/spawn-sync/lib/spawn-sync.js
Module not found: Error: Cannot resolve module 'try-thread-sleep' in /home/edward/electron-mattermost/src/node_modules/spawn-sync/lib
 @ ./src/~/spawn-sync/lib/spawn-sync.js 10:10-37
```

**Comment by yuya-oc** [comment]
I have markupped logs to read.

Did `npm install` finished correctly? This error indicates `npm run build` also fails. It's executed in `npm install`.

Please tell me your environment:
* OS
* Node.js and npm version

**Comment by etcy** [comment]
I'm running blacklab linux guest on a win 7 host. 
I had previously built mattermost-electron v1.01 with no problems or warnings.

1. Version info
npm -v 
3.3.12
node -v
v5.4.0
uname -r
3.19.0-43-generic

2. Npm install gave similiar warnings as my original post:
edward@edward-VirtualBox:~/electron-mattermost$ npm install
npm WARN install Couldn't install optional dependency: Unsupported

> electron-mattermost@1.0.5 install /home/edward/electron-mattermost
> cd src && npm install

npm WARN EPACKAGEJSON electron-mattermost@1.0.5 No repository field.

> electron-mattermost@1.0.5 postinstall /home/edward/electron-mattermost
> npm run build


> electron-mattermost@1.0.5 build /home/edward/electron-mattermost
> gulp build

[10:51:12] Using gulpfile ~/electron-mattermost/gulpfile.js
[10:51:12] Starting 'sync-meta'...
[10:51:12] Finished 'sync-meta' after 8.29 ms
[10:51:12] Starting 'webpack:main'...
[10:51:13] Starting 'webpack:browser'...
[10:51:13] Starting 'webpack:webview'...
[10:51:13] Starting 'copy:resources'...
[10:51:13] Starting 'copy:html/css'...
[10:51:13] Starting 'copy:modules'...
[10:51:13] Version: webpack 1.12.13
        Asset     Size  Chunks             Chunk Names
mattermost.js  6.93 kB       0  [emitted]  mattermost
[10:51:14] Finished 'copy:resources' after 1.38 s
[10:51:14] Finished 'webpack:webview' after 1.55 s
[10:51:14] Finished 'copy:html/css' after 1.59 s
[10:51:17] Version: webpack 1.12.13
  Asset    Size  Chunks             Chunk Names
main.js  757 kB       0  [emitted]  main

WARNING in ./src/main.js
Critical dependencies:
117:21-46 the request of a dependency is an expression
 @ ./src/main.js 117:21-46

WARNING in ./src ^\.\/.*$
Module not found: Error: a dependency to an entry point is not allowed
 @ ./src ^\.\/.*$

WARNING in ./src ^\.\/.*$
Module not found: Error: a dependency to an entry point is not allowed
 @ ./src ^\.\/.*$

WARNING in ./src/~/yargs/lib/parser.js
Critical dependencies:
359:21-48 the request of a dependency is an expression
 @ ./src/~/yargs/lib/parser.js 359:21-48

WARNING in ./src/browser/css/jp_fonts.css
Module parse failed: /home/edward/electron-mattermost/src/browser/css/jp_fonts.css Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| @font-face {
|   font-family: sans-serif;
|   src: local('Meiryo UI');
 @ ./src ^\.\/.*$

WARNING in ./src/browser/index.html
Module parse failed: /home/edward/electron-mattermost/src/browser/index.html Line 1: Unexpected token <
You may need an appropriate loader to handle this file type.
| <!DOCTYPE html>
| <html>
| 
 @ ./src ^\.\/.*$

WARNING in ./src/browser/index.jsx
Module parse failed: /home/edward/electron-mattermost/src/browser/index.jsx Line 131: Unexpected token <
You may need an appropriate loader to handle this file type.
|     if (this.props.teams.length > 1) {
|       tabs_row = (
|         <Row>
|           <TabBar id="tabBar" teams={ this.props.teams } unreadCounts={ this.state.unreadCounts } mentionCounts={ this.state.mentionCounts } unreadAtActive={ this.state.unreadAtActive } mentionAtActiveCounts={ this.state.mentionAtActiveCounts }
|             activeKey={ this.state.key } onSelect={ this.handleSelect }></TabBar>
 @ ./src ^\.\/.*$

WARNING in ./src/browser/settings.html
Module parse failed: /home/edward/electron-mattermost/src/browser/settings.html Line 1: Unexpected token <
You may need an appropriate loader to handle this file type.
| <!DOCTYPE html>
| <html>
| 
 @ ./src ^\.\/.*$

WARNING in ./src/browser/settings.jsx
Module parse failed: /home/edward/electron-mattermost/src/browser/settings.jsx Line 65: Unexpected token <
You may need an appropriate loader to handle this file type.
|   render: function() {
|     var teams_row = (
|     <Row>
|       <Col md={ 12 }>
|       <h2>Teams</h2>
 @ ./src ^\.\/.*$

WARNING in ./src/resources/appicon.png
Module parse failed: /home/edward/electron-mattermost/src/resources/appicon.png Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./src ^\.\/.*$

WARNING in ./src/resources/tray.png
Module parse failed: /home/edward/electron-mattermost/src/resources/tray.png Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./src ^\.\/.*$

WARNING in ./src/~/ws/lib/Validation.js
Module not found: Error: Cannot resolve module 'utf-8-validate' in /home/edward/electron-mattermost/src/node_modules/ws/lib
 @ ./src/~/ws/lib/Validation.js 10:19-44

WARNING in ./src/~/ws/lib/BufferUtil.js
Module not found: Error: Cannot resolve module 'bufferutil' in /home/edward/electron-mattermost/src/node_modules/ws/lib
 @ ./src/~/ws/lib/BufferUtil.js 10:19-40

WARNING in ./src/~/spawn-sync/lib/spawn-sync.js
Module not found: Error: Cannot resolve module 'try-thread-sleep' in /home/edward/electron-mattermost/src/node_modules/spawn-sync/lib
 @ ./src/~/spawn-sync/lib/spawn-sync.js 10:10-37
[10:51:17] Finished 'webpack:main' after 4.74 s
[10:51:17] Version: webpack 1.12.13
      Asset     Size  Chunks             Chunk Names
   index.js  1.18 MB       0  [emitted]  index
settings.js  1.17 MB       1  [emitted]  settings
[10:51:17] Finished 'webpack:browser' after 4.27 s
[10:51:17] Starting 'webpack'...
[10:51:17] Finished 'webpack' after 10 μs
[10:51:17] Finished 'copy:modules' after 4.27 s
[10:51:17] Starting 'copy'...
[10:51:17] Finished 'copy' after 3.11 μs
[10:51:17] Starting 'build'...
[10:51:17] Finished 'build' after 3.13 ms
npm WARN EPACKAGEJSON electron-mattermost@1.0.5 No repository field.

-----------------------------
*sorry... could you teach me how to markup the logs to read properly... copy n paste from the txt files directly screws up the view

**Comment by yuya-oc** [comment]
Currently, `npm run build` shows warning, but no problem. Besides I tried with ubuntu 14.04 64bit, node 5.4.0, npm 3.3.12. `npm run package:windows` succeeded (not tested app behavior).

In the second log, it seems `npm run build` succeeded because `Finished 'build' after 3.13 ms` appeared. Please try `npm run package:windows`? Compiled packages will be created in `release/` directory.

btw, [this page](https://guides.github.com/features/mastering-markdown/) is nice to understand **Markdown**. I had used following syntax.

> \`\`\`
> some
> codes
> \`\`\`

**Comment by etcy** [comment]
Tks for the reply. I tried to build on a linuxmint 17.3 earlier, still getting the warnings.

Just wondering... Do you get the same warnings when you built on Ubuntu 14.04 64bit?

**Comment by yuya-oc** [comment]
Yes. You can see build logs in [CircleCI](https://circleci.com/gh/yuya-oc/electron-mattermost). In future, these warning should be fixed.

Please reopen this when you need.
