### ISSUE TITLE
Desktop notifications not working with Mattermost 2.0

### ISSUE THREAD

**Issue by etcy** [yuya-oc/electron-mattermost#36]
I tried the prebuilt versions, both 32bit, 64bit on 4 machines and the desktop notifications does not work.

Did i miss some information? Do i need to setup anything for it to work?

Server is running v2.0 mattermost. Desktop notifications work for chrome browser.

Is there any info I can provide to help debug this?

**Comment by yuya-oc** [comment]
Generally, you don't have to do anything in setup. Desktop notification should work as default.

The issue happens with Mattermost v2.0. I had not tested yet.
Maybe this issue is caused by `src/browser/webview/mattermost.js`.

**Comment by etcy** [comment]
I see. Previously I was running 1.4 mattermost but it had the "would not auto scroll" on new message bug. 2.0 mattermost has it solved. Too bad the desktop notification is now broken. Funny thing is it works on Chrome. 

When you said it might be related to mattermost.js, do you know of any temp fix for it?

**Comment by yuya-oc** [comment]
Please comment out [this overriding part](https://github.com/yuya-oc/electron-mattermost/blob/3168135082773d4a06cf5d195b47252c76db2bbd/src/browser/webview/mattermost.js#L150-L155), then build the app.
As side effect, the window will not get focus when you click a notification in Win10 and OS X.

**Comment by yuya-oc** [comment]
Sorry, I forgot importtant point. Desktop notification will not work in Windows 7 and 8. On Windows 7, Electron can't use Desktop notification, so I overrided to use ballon. However, in this case, the overriding doesn't work correctly.
