### ISSUE TITLE
Disable sound on receive message

### ISSUE THREAD

**Issue by i23098** [yuya-oc/electron-mattermost#38]
There should be a way to disable sound on receive message. At least, disable it if conversation has focus

**Comment by yuya-oc** [comment]
The sound is controlled by Mattermost. It's available at `Menu -> Account Settings -> Notifications`.

**Comment by i23098** [comment]
Thanks :) Closing the bug then...

**Comment by f3l1x** [comment]
GUI guide for others:

![zales_-_ders_ders_group_](https://cloud.githubusercontent.com/assets/538058/21264686/c7bf66fa-c39d-11e6-88a0-b93e37986962.png)

**Comment by ahttraga** [comment]
In linux client 4.6.1 I don't have the option to disable sound.

![image](https://user-images.githubusercontent.com/54644739/105016589-1bc2ec00-5a43-11eb-9bb4-cd72489df4c3.png)
