### ISSUE TITLE
Windows spawn off-screen on Windows 8.1

### ISSUE THREAD

**Issue by GhostLyrics** [yuya-oc/electron-mattermost#44]
- Windows 8.1
- 64 bit
- electron-mattermost v 1.0.7

When program is started, windows spawn off-screen and are not movable/clickable. Off-screen position is assumed from animation when minimizing/restoring the window via the Windows taskbar.

**Comment by yuya-oc** [comment]
After quitting the app, please remove `%USERPROFILE%\AppData\Roaming\electron-mattermost\bounds-info.json`.

**Comment by ajscilingo** [comment]
I had this problem recently too in Windows 10 using version 3.6.1 of the Mattermost Client, deleting the bounds-info.json fixed it, thanks.

**Comment by yuya-oc** [comment]
FYI, upcoming v3.6.0 desktop app would fix this issue.

**Comment by ajscilingo** [comment]
I'm using v3.6.1 of the Desktop App, I am however using a multi monitor setup (3 monitors), 2 of which are at 1080p and one of which is at 4K.  The DPI is different from the 4K and 1080p Displays, which I'm guessing might have something to do with what happened.

**Comment by yuya-oc** [comment]
v3.6.1 doesn't exist (the latest is v3.5.0). Probably it's the version of the Mattermost server.

I feel that DPI is not related to this issue. But I'm not sure in detail though, it's a little hard to test for me.
By the way, possibly there might be another issue in multi DPI environment of Windows. Please see #357

**Comment by ajscilingo** [comment]
It says in my About Mattermost Client, Mattermost Enterprise Edition Version 3.6.0 (3.6.1)

**Comment by ajscilingo** [comment]
But funny, if I push the alt key and click on the help menu it says in the menu as a grayed out menu item Version 3.5.0

**Comment by jasonblais** [comment]
Ah yes, the About Mattermost dialog is referring to the server; the help menu is for the client version.

Desktop App v3.6.0 should fix the issue, which is scheduled to release on Tuesday
