### ISSUE TITLE
Feature request: An easier way to input emoji

### ISSUE THREAD

**Issue by etcy** [yuya-oc/electron-mattermost#49]
I have been testing the server/client on a small scale (about 15 members).

Since only a handful are programmer/scriptors, many find it hard to input emoji
using the markdown language directly....

Is there anyway we can improve this by providing some sort of GUI for such users.

**Comment by yuya-oc** [comment]
Now Mattermost has emoji-completion. Is thi not enough?

![2016-03-01 20 54 26](https://cloud.githubusercontent.com/assets/1412057/13426447/c7c4ef80-dff0-11e5-97ef-45e75cf97fdb.png)

I think this should be improved by Mattermost side. The completion will be independent from any clients.

**Comment by alerque** [comment]
Yes, this should be an upstream Mattermost issue, not a client issue.

**Comment by etcy** [comment]
1. Sadly,  autocomplete is not enough, since you have to know what emoji there are in the first place.
I think the best explanation i can offer is from a user who compared it to a popular chat program in Japan called "line" where you can choose the emoji from a table (though it has intelisense as well)

2. Sorry I was not sure if this could be done on client side or server side.
Since this is a server issue, I will try to raise the issue there. 

Thank you.

**Comment by alerque** [comment]
Yes, if you want a popup box to insert any available emoji this would be best implemented in Mattermost itself. As a wrapper around a web interface, this electron app wouldn't be able to implement this very smoothly even if it wanted to and I for one would object to a feature that tried (as it would inevitably break the normal input mechanism).

Please suggest this upstream and close this issue.
