### ISSUE TITLE
[OS X] Notifications in Notification Center disappears as soon as notification hides

### ISSUE THREAD

**Issue by nItroFreeZer** [yuya-oc/electron-mattermost#53]
The notification (2) in Notification Center disappears automatically as soon as the notification (1) hides after a few seconds.
Is there a way to fix this?
And is ist possible that the notification (1) does not hide automatically?

![bildschirmfoto 2016-03-03 um 09 49 56](https://cloud.githubusercontent.com/assets/1172623/13489298/7f4eb6e6-e126-11e5-9064-f57efab60026.png)

**Comment by yuya-oc** [comment]
Both no, it's controlled by Electron and OS X. So I can't fix it.
