### ISSUE TITLE
[Cross Platform] [enhancement] Check if Matermost server is reachable

### ISSUE THREAD

**Issue by frdmn** [yuya-oc/electron-mattermost#54]
We currently play around with Mattermost to evaluate if it is suitable as internal chat system for our company. So we try a lot of clients and integration to make it as comfortable for our (sometimes not that "technically adept") co-workers. 

In our test phase, we use `electron-mattermost` as Mac client, and often trash the MM server (try stable/dev versions, install SSL, using Docker/non-Docker) etc. so it happend that the URI switched from `http://mattermost.intern.company.de:8065` to `https://mattermost.intern.company.de` (proper HTTPS port) but electron didn't notice that the server is not reachable anymore and just responded with a blank page.

People then needed manually to go into the Settings and replace the non-exisiting MM server with the replacement one.

I think, that if there is a not reachable server, `electron-mattermost` should simply redirect the user to the settings view and perhaps with a simple warning message to let the users know what happened.

What do you think?

**Comment by nItroFreeZer** [comment]
+1

The same happened to me today.

**Comment by yuya-oc** [comment]
Yes, the app should raise error messages. (#14)

However, there are some reasons for unreachable (e.g. computer is offline, server is down, ...). Users may be able to load Mattermost by reloading so I think the redirect is too much.

**Comment by frdmn** [comment]
Okay, I agree but letting the user know that something went south is really required then. :)

Should I close this issue since its a duplicate or relevant to #14?

**Comment by yuya-oc** [comment]
I will close. Thank you for your feedback!
