### ISSUE TITLE
Can't quit the application on Windows

### ISSUE THREAD

**Issue by clorteau** [yuya-oc/electron-mattermost#8]
Windows 7 pro 64 bits. electron-mattermost release 1.0.1 64 bits.

Clicking the close button minimizes the window. There's no quit button. Logging out in the app doesn't close the app. Multiple electron-mattermost.exe processes exist and all must be killed to quit.

**Comment by yuya-oc** [comment]
On Windows, there are three methods to quit.

1. Press Ctrl+Q (written in README)
2. Show menu bar by pressing Alt key, then select 'File'->'Quit'.
3. Click tray icon, then select 'Quit'.

**Comment by clorteau** [comment]
Oh, I didn't see the tray icon nor did I read the README... My bad.

Maybe a 1st run feature (popup, balloons...) showing that you can show the menu bar and that there's a tray icon could help. Just my 2 cents.

**Comment by yuya-oc** [comment]
Thanks, I will consider some solution for "how to quit".
